export const SET_CLIENTS= 'SET_CLIENTS';
export const SET_PARTNERS= 'SET_PARTNERS';
export const SET_ONE_PARTNER= 'SET_ONE_PARTNER';
export const SET_ONE_CLIENTS= 'SET_ONE_CLIENTS';
export const HANDLE_DIALOG= 'HANDLE_DIALOG';
export const SET_PROBLEM= 'SET_PROBLEM';